# Mini-proyecto: Clasificación multiclase en Wine

- Preparar datos (split estratificado, estandarización sin fuga)
- Entrenar Regresión Logística Multinomial (Softmax) con `lbfgs`
- Evaluar con classification_report, matriz de confusión, ROC/AUC macro y micro.
- Hacer búsqueda de hiperparámetros (GridSearchCV) de forma segura.
- Interpretar coeficientes del modelo y revisar errores

## 1. Instalación de librerias necesarias para ejecutar el código.

- load_wine = llamamos al dataset que usaremos.
- train_test_split = nos permite sepaparar el dataset para entrenamiento y testeo.
- GridSearchCV = se ejecuta a través de los diferentes parámetros que se introducen en la cuadrícula de parámetros y extraer los mejores valores y combinaciones de parámetros.
- StandardScaler = estandariza los datos eliminando la media y escalando los datos de forma que su varianza sea igual a 1.

    ``` python
        from sklearn.preprocessing import StandardScaler
        data = [[0,0],[0,0],[1,1],[1,1]]
        scaler = StandardScaler()
        print(scaler.fit(data))
        # StandardScaler()
        print(scaler.mean_)
        # [0.5 0.5]
        print(scaler.transform(data))
        # [[-1. -1.]
        # [-1. -1.]
        # [ 1.  1.]
        # [ 1.  1.]]
    ```

- label_binarize = convierte las etiquetas de categorias en vectores binarios

    ``` python
        from sklearn.preprocessing import
        a = label_binarize(['yes','no','no','yes'], classes=['no','yes'])
        print(a)
        # [[1]
        # [0]
        # [0]
        # [1]]
        a = label_binarize([1,6], classes=[1,6,4,2,])
        print(a)
        # [[1 0 0 0]
        # [0 1 0 0]]
    ```


In [9]:
from sklearn.datasets import load_wine 
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, label_binarize
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    classification_report, confusion_matrix, f1_score, roc_curve,auc, roc_auc_score
)
import numpy as np
import matplotlib.pyplot as plt

data = [[0,0],[0,0],[1,1],[1,1]]
scaler = StandardScaler()
print(scaler.fit(data))
print(scaler.mean_)
print(scaler.transform(data))

StandardScaler()
[0.5 0.5]
[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]
