# Intriducción a NumPy

NumPy (Numerical Python) es la libreria más usada para trabajar con matrices y calculos numéricos en Python

## Instalación
pip install numpy

## Crear arrays

In [3]:
import numpy as np
# array 1D
arr = np.array([1, 2, 3, 4])
print(arr)

# array 2D
matriz = np.array([[1,2,3], [4,5,6]])
print(matriz)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


## Propiedades de un array

In [ ]:
print(arr.shape) # dimensiones
print(arr.ndim) # muestra el número de dimensiones en el array
print(arr.size) # cantidad ded elementos
print(arr.dtype) # tipo de dato

(4,)
1
4
int32


## Operaciones matematicas 

NumPy permite operaciones matematicas sin necesidad del uso de bucles

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a * b)
print(a ** 2)

[5 7 9]
[ 4 10 18]
[1 4 9]


## Funciones útiles

In [9]:
print(np.zeros((2,2)))
print(np.ones((3,3)))
print(np.arange(0,10,2)) #crea array seleccionando inicio, final y pasos
print(np.linspace(0,1,5)) # puedes hacer un array seleccionando el numero de intervalos

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


## Indexación y slicing

In [15]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0]) # 10
print(arr[1:4]) # [20 30 40]

mat = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(mat[0,0]) # 1
print(mat[:,1]) # Columna 1
print(mat[1,:]) # Fila 1

10
[20 30 40]
1
[2 5 8]
[4 5 6]


In [2]:
import numpy as np
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)

print("Elemento (0,1):", matriz[0,1])  # 2
print("Primera fila:", matriz[0])      # [1 2 3]
print("Columna 2:", matriz[:,1])       # [2 5 8]


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Elemento (0,1): 2
Primera fila: [1 2 3]
Columna 2: [2 5 8]


In [3]:
arr = np.array([1, 2, 3, 4])

print(arr + 10)   # [11 12 13 14]
print(arr * 2)    # [2 4 6 8]
print(arr ** 2)   # [1 4 9 16]


[11 12 13 14]
[2 4 6 8]
[ 1  4  9 16]


In [4]:
arr = np.array([1, 2, 3, 4, 5])

print("Suma:", np.sum(arr))           # 15
print("Promedio:", np.mean(arr))      # 3.0
print("Desviación estándar:", np.std(arr))  # 1.4142...
print("Mínimo:", np.min(arr))         # 1
print("Máximo:", np.max(arr))         # 5


Suma: 15
Promedio: 3.0
Desviación estándar: 1.4142135623730951
Mínimo: 1
Máximo: 5


In [5]:
# Multiplicacion de matrices
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Producto matricial:\n", np.matmul(A,B))


Producto matricial:
 [[19 22]
 [43 50]]


In [22]:
# 1. Crea un array con los números del 1 al 10 y muestra el 3er, 5to y 7mo elemento

arr = np.arange(1,11,1)
print(arr)

print(arr[2])
print(arr[4])
print(arr[6])

[ 1  2  3  4  5  6  7  8  9 10]
3
5
7


In [26]:
# 2. Crea una matriz 3x3 con los valores del 1 al 9 y muestra su diagonal

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

print(arr.diagonal())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [28]:
# 3. Genera un array con 20 números del 0 al 100 usando linspace

arr = np.linspace(0,100,20)
print(arr)

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]


In [30]:
# 4. Calcula el cuadrado de cada número en [2, 4, 6, 8]

arr = np.arange(2,9,2)
print(arr**2)


[ 4 16 36 64]


In [31]:
# 5. Suma todas las filas de la matriz:

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
suma = arr.sum(axis=1)
print(suma)

[ 6 15 24]


In [32]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
print(np.exp([1,2,3]))

[ 2.71828183  7.3890561  20.08553692]
