# Intriducción a NumPy

NumPy (Numerical Python) es la libreria más usada para trabajar con matrices y calculos numéricos en Python

## Instalación
pip install numpy

## Crear arrays

In [3]:
import numpy as np
# array 1D
arr = np.array([1, 2, 3, 4])
print(arr)

# array 2D
matriz = np.array([[1,2,3], [4,5,6]])
print(matriz)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


## Propiedades de un array

In [ ]:
print(arr.shape) # dimensiones
print(arr.ndim) # muestra el número de dimensiones en el array
print(arr.size) # cantidad ded elementos
print(arr.dtype) # tipo de dato

(4,)
1
4
int32


## Operaciones matematicas 

NumPy permite operaciones matematicas sin necesidad del uso de bucles

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a * b)
print(a ** 2)

[5 7 9]
[ 4 10 18]
[1 4 9]


## Funciones útiles

In [8]:
print(np.zeros((2,2)))
print(np.ones((3,3)))
print(np.arange(0,10,2))
print(np.linspace(0,1,5))

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
