# NumPy II

- Array = coleccion de datos homogéneos y optimizados para cálculos
- Se pueden hacer operaciones vectorizadas sin bucles

In [3]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(np.sum(arr)) # suma
print(np.prod(arr)) # multiplicar
print(np.min(arr)) # muestra el numero mas bajo
print(np.max(arr)) # muestra el nimero mas alto
print(np.sqrt(arr)) # raiz cuadrada de cada elemento
print(np.exp(arr)) # e^x para cada elemento
print(np.log(arr)) # logaritmo natural

15
120
1
5
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


## Funciones estadisticas

In [ ]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(np.mean(arr)) # media: 30
print(np.median(arr)) # mediana: 30
print(np.std(arr)) # desviacion estandar
print(np.var(arr)) # varianza
print(np.percentile(arr, 50))



30.0
30.0
14.142135623730951
200.0
30.0


## Operaciones con matrices

In [4]:
A = np.array([[1,2], [2,3]])
B = np.array([[5,6], [7,8]])

print(A + B)
print(A - B)
print(A * B) # Multiplicacion elemento a elemento
print(np.dot(A, B)) # Multiplicacion matricial
print(A.T) # Transpuesta

[[ 6  8]
 [ 9 11]]
[[-4 -4]
 [-5 -5]]
[[ 5 12]
 [14 24]]
[[19 22]
 [31 36]]
[[1 2]
 [2 3]]


In [ ]:
import numpy as np

notas = np.array([
    [15,12,18],
    [10,14,16],
    [20,19,17]
])

print("Promedio por alumno: ", np.mean(notas, axis=1)) # FILA
print("Promedio por curso: ", np.mean(notas, axis=0)) # COLUMNA

Promedio por alumno:  [15.         13.33333333 18.66666667]
Promedio por curso:  [15. 15. 17.]


In [5]:
# 1. Crea un array con [5, 10, 15, 20,25] y calcula: suma, producto, minimo y maximo
import numpy as np

arr = np.array([5,10,15,20,25])
print("Suma: ",np.sum(arr))
print("Producto: ",np.prod(arr))
print("Minimo: ", np.min(arr))
print("Maximo: ", np.max(arr))

Suma:  75
Producto:  375000
Minimo:  5
Maximo:  25


In [8]:
# 2. Crea un array [2,4,6,8] y calcula: raiz cuadrada, e^x, logaritmo

import numpy as np

arr = np.array([2,4,6,8])
print("Raiz cuadrada: ", np.sqrt(arr))
print("e^x: ", np.exp(arr))
print("Logaritmo: ", np.log(arr))


Raiz cuadrada:  [1.41421356 2.         2.44948974 2.82842712]
e^x:  [   7.3890561    54.59815003  403.42879349 2980.95798704]
Logaritmo:  [0.69314718 1.38629436 1.79175947 2.07944154]


In [ ]:
# 3. Con [1, 2, 3, 4, 5, 6, 7, 8, 9], calcula: media, mediana, desviación estándar.
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])

print("Media: ", np.mean(arr))
print("Mediana: ", np.median(arr))
print("Desviacion estandar: ", np.std(arr))

Media:  5.0
Mediana:  5.0
Desviacion estandar:  2.581988897471611


In [18]:
# 4. Multicplica las matrices
import numpy as np
A = [[1,2,3],[4,5,6]]
B = [[7,8],[9,10],[11,12]]

print("Multiplicacion de las matrizes: ", np.matmul(A,B))

Multiplicacion de las matrizes:  [[ 58  64]
 [139 154]]


In [24]:
# 5. Crea un array 3x3 con notas de alumnos y muestra el promedio de cada alumno y de cada curso.
import numpy as np

notas = [
    [10, 16, 20],
    [15, 5, 13],
    [6, 11, 13]
]
print(f"Pomedio de notas del alumno : ", np.mean(notas, axis=1))

Pomedio de notas del alumno :  [15.33333333 11.         10.        ]


In [25]:
import math

print(math.e(1))

TypeError: 'float' object is not callable